version: '3.9'
services: 
  service1:  
    build : ./service_1
    networks: 
      mynetwork:
        ipv4_address: "192.168.1.4"
    ports: 
      - "50:8000"
  service2:
    build: ./service_2
    networks:
      mynetwork:
        ipv4_address: "192.168.1.5"
    ports:
      - "3000:3000"

  
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24


